{
 "title": "Expenses Dashboard",
 "description": "Visualize various statistics about your expenses",
 "time": { "from": "2025-01-24T05:00:00.000Z", "to": "2025-02-25T04:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "monthly_income", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Total spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)\nfrom expenses \nwhere $__timeFilter(\"date\"); "
    }
   ]
  },
  {
   "title": "Total spent on needs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)\nfrom expenses \nwhere $__timeFilter(\"date\")\nand tipo = 'need'; "
    }
   ]
  },
  {
   "title": "Total spent on wants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)\nfrom expenses \nwhere $__timeFilter(\"date\")\nand tipo = 'want' "
    }
   ]
  },
  {
   "title": "% total spent ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (sum(amount) / $monthly_income) * 100\nfrom expenses\nwhere $__timeFilter(\"date\"); "
    }
   ]
  },
  {
   "title": "% spent on needs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (sum(amount) / $monthly_income) * 100\nfrom expenses\nwhere $__timeFilter(\"date\")\nand tipo = 'need'; "
    }
   ]
  },
  {
   "title": "% spent on wants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (sum(amount) / $monthly_income) * 100\nfrom expenses\nwhere $__timeFilter(\"date\")\nand tipo = 'want'; "
    }
   ]
  },
  {
   "title": "# total expenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from expenses where $__timeFilter(\"date\") "
    }
   ]
  },
  {
   "title": "# need expenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom expenses\nwhere $__timeFilter(\"date\")\nand tipo = 'need';"
    }
   ]
  },
  {
   "title": "# want expenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom expenses\nwhere $__timeFilter(\"date\")\nand tipo = 'want';"
    }
   ]
  },
  {
   "title": "Wants over time",
   "type": "timeseries",
   "description": "Show expenses that are \"wants\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, SUM(amount) as \"Spent per day\"\nFROM expenses \nwhere tipo = 'want'\nand $__timeFilter(\"date\") \ngroup by date\norder by date desc\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Needs over time",
   "type": "timeseries",
   "description": "Show expenses that are \"needs\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, SUM(amount) as \"Spent per day\"\nFROM expenses \nwhere tipo = 'need'\nand $__timeFilter(\"date\") \ngroup by date\norder by date desc\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "What you have spent on",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select reference, count(*)\nfrom expenses\nwhere $__timeFilter(\"date\") \nand reference <> ''\ngroup by reference;"
    }
   ]
  }
 ]
}