apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: db:5432
    user: S32EFV
    uid: 'ae11ec75-ace0-4fc3-b7ac-2de6072bb7db'
    secureJsonData:
      password: 'S32EFV'
    jsonData:
      database: S32EFV
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false
